Importing libraries for project

In [188]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

Loading the dataset

In [189]:
Drug=pd.read_csv('Drug (1).csv')
Drug.head()

   Age Sex      BP Cholesterol        Na         K   Drug
0   23   F    HIGH        HIGH  0.792535  0.031258  drugY
1   47   M     LOW        HIGH  0.739309  0.056468  drugC
2   47   M     LOW        HIGH  0.697269  0.068944  drugC
3   28   F  NORMAL        HIGH  0.563682  0.072289  drugX
4   61   F     LOW        HIGH  0.559294  0.030998  drugY

In [190]:
Drug.describe()

              Age          Na           K
count  200.000000  200.000000  200.000000
mean    44.315000    0.697095    0.050174
std     16.544315    0.118907    0.017611
min     15.000000    0.500169    0.020022
25%     31.000000    0.583887    0.035054
50%     45.000000    0.721853    0.049663
75%     58.000000    0.801494    0.066000
max     74.000000    0.896056    0.079788

Checking for any null value

In [191]:
Drug.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na             0
K              0
Drug           0
dtype: int64

Data preprocessing

In [192]:
numerical_features=['Age','Na','K']
categorical_features=['Sex','BP','Cholesterol']

In [193]:
for i in categorical_features:
  le = LabelEncoder()
  Drug[i]=le.fit_transform(Drug[i])

In [194]:
scaler=StandardScaler()
Drug[numerical_features]=scaler.fit_transform(Drug[numerical_features])

In [195]:
Drug.head()

        Age  Sex  BP  Cholesterol        Na         K   Drug
0 -1.291591    0   0            0  0.804654 -1.076762  drugY
1  0.162699    1   1            0  0.355905  0.358283  drugC
2  0.162699    1   1            0  0.001465  1.068462  drugC
3 -0.988614    0   2            0 -1.124809  1.258871  drugX
4  1.011034    0   1            0 -1.161804 -1.091562  drugY

BUILDING THE MODEL

In [196]:
from sklearn.model_selection  import train_test_split

In [197]:
x=Drug.drop('Drug',axis=1)
y=Drug['Drug']
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.05,random_state=42)

In [198]:
from sklearn.tree import DecisionTreeClassifier

In [199]:
model=DecisionTreeClassifier(max_depth=4,random_state=42)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [200]:
y_pred= model.predict(X_test)

Checking the Accuracy

In [201]:
from sklearn.metrics import accuracy_score

In [202]:
acc=accuracy_score(y_test,y_pred)
acc

0.9

Applying the model on unknown data

In [203]:
age=56
sex="M"
bp="LOW"
chol="HIGH"
na=0.1
k=0.045

sex_map={'M':1,'F':0}
bp_map={'LOW':1,'NORMAL':2,'HIGH':0}
chol_map={'NORMAL':1,'HIGH':0}

sex=sex_map[sex]
bp=bp_map[bp]
chol=chol_map[chol]
new_data=pd.DataFrame([[age,sex,bp,chol,na,k]],columns=['Age','Sex','BP','Cholesterol','Na','K'])
new_data[numerical_features]=scaler.transform(new_data[numerical_features])
new_data
prediction=model.predict(new_data)
print("Predicted Drug:",prediction[0])

Predicted Drug: drugX